# Generated by Django 3.2.5 on 2021-07-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=25)),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
